from __future__ import annotations

from datetime import date
from pathlib import Path

from .schema import Schema, Table


def _page(table: Table) -> str:
    rows = "\n".join(
        f"| `{column.name}` | `{column.type}` | {'yes' if column.name in table.primary_key else ''} | {'no' if not column.nullable else 'yes'} |"
        for column in table.columns
    )
    return f"""---
type: implementation
tags:
  - schema
  - autogenerated
updated: {date.today().isoformat()}
---

This generated page describes the `{table.name}` database table from `schema/sql/`.

# `{table.name}`

Source file: `{table.source_file}`

## Columns

| Column | Type | Primary key | Nullable |
| --- | --- | --- | --- |
{rows}

## Sources

- `schema/sql/{table.source_file}`
"""


def _index(schema: Schema) -> str:
    rows = "\n".join(
        f"| [`{name}`](./{name.replace('.', '__')}.md) | {len(schema.tables[name].columns)} | `{schema.tables[name].source_file}` |"
        for name in schema.table_names()
    )
    return f"""---
type: implementation
tags:
  - schema
  - autogenerated
updated: {date.today().isoformat()}
---

This generated page indexes database schema reference pages from `schema/sql/`.

# Generated Schema Reference

| Table | Columns | Source |
| --- | ---: | --- |
{rows}

## Sources

- `schema/sql/`
"""


def generate(schema: Schema, wiki_dir: Path) -> list[Path]:
    out_dir = wiki_dir / "generated" / "schema"
    out_dir.mkdir(parents=True, exist_ok=True)
    written: list[Path] = []
    index_path = out_dir / "index.md"
    index_path.write_text(_index(schema), encoding="utf-8")
    written.append(index_path)
    for table in schema.tables.values():
        path = out_dir / f"{table.name.replace('.', '__')}.md"
        path.write_text(_page(table), encoding="utf-8")
        written.append(path)
    return written
